package report

var AllCodes = map[string]string{
	"CERT-001": "No certificate presented",
	"CERT-010": "Certificate not yet valid",
	"CERT-011": "Certificate expired",
	"CERT-012": "Certificate expires soon",
	"CERT-013": "Certificate expiry approaching",
	"CERT-020": "Certificate hostname mismatch",
	"CERT-021": "Certificate chain is not trusted",
	"CERT-030": "Weak certificate signature algorithm",
	"CERT-031": "Weak RSA key size",
	"CERT-032": "RSA key size acceptable but not strong",
	"CERT-033": "Weak ECDSA curve",
	"CERT-034": "Unexpected public key type",
	"CERT-040": "No SCTs observed",
	"CERT-041": "No OCSP responder URI",
	"CERT-042": "No CRL distribution points",
	"CERT-043": "SCTs present (embedded extension)",
	"CERT-050": "Leaf certificate marked as CA",
	"CERT-051": "Invalid basic constraints",
	"CERT-052": "No intermediates presented",
	"CERT-053": "Non-CA certificate in chain",
	"CERT-054": "Expired intermediate in chain",
	"CERT-055": "SHA-1 signed intermediate",
	"CERT-056": "Weak RSA intermediate key",
	"CERT-057": "Short-lived certificate",
	"CERT-060": "Extended key usage includes any",
	"CERT-061": "Missing serverAuth extended key usage",
	"CERT-062": "Encipherment-only key usage",
	"CERT-063": "Multiple wildcards in SAN",
	"CERT-064": "Wildcard SAN may not cover requested host",

	"DNS-001": "DNS resolution failed",
	"DNS-002": "No A/AAAA records",
	"DNS-003": "Multiple IPs detected",
	"DNS-010": "No CAA records found",
	"DNS-011": "CAA records found",
	"DNS-012": "CAA policy does not authorize observed issuer",
	"DNS-020": "Dual-stack DNS detected",
	"DNS-021": "IPv6-only DNS detected",
	"DNS-022": "IPv4-only DNS detected",
	"DNS-030": "TLSA records present but cert digest unavailable",
	"DNS-031": "TLSA matches presented certificate",
	"DNS-032": "TLSA policy mismatch",

	"EDGE-001": "TLS version inconsistency across IPs",
	"EDGE-002": "Cipher suite inconsistency across IPs",
	"EDGE-003": "Certificate inconsistency across IPs",
	"EDGE-004": "IPv4 vs IPv6 leaf certificate mismatch",
	"EDGE-005": "Different public keys across IPs",

	"HTTP-001": "HTTP redirect check failed",
	"HTTP-002": "HTTP does not clearly redirect to HTTPS",
	"HTTP-003": "HTTP redirects to HTTPS",
	"HTTP-004": "Redirect chain inspection failed",
	"HTTP-005": "Redirect chain downgraded to HTTP",
	"HTTP-006": "Long redirect chain",
	"HTTP-007": "Redirect changed hostname",
	"HTTP-010": "HTTPS fetch failed",
	"HTTP-011": "HSTS header missing",
	"HTTP-012": "HSTS disabled or low",
	"HTTP-013": "HSTS does not include subdomains",
	"HTTP-015": "HTTP security header issue",
	"HTTP-020": "Cookie security flags are incomplete",
	"HTTP-030": "Possible mixed content detected",
	"HTTP-031": "Active HTTPS subresource host has TLS errors",
	"HTTP-040": "HTTP/3 advertised",

	"NET-001": "TCP connection failed",
	"NET-002": "Address family unreachable from scanner (routing)",

	"POL-001": "Profile requires CAA",
	"POL-003": "Strict profile: CAA does not authorize issuer",
	"POL-004": "Strict profile: Must-Staple not satisfied",
	"POL-005": "Strict profile: no CT/SCT evidence",
	"POL-006": "Strict profile: no CRL distribution points",

	"TLS-001": "TLS handshake failed",
	"TLS-010": "Legacy TLS negotiated",
	"TLS-011": "Legacy TLS version supported",
	"TLS-012": "No modern TLS support",
	"TLS-020": "No ALPN negotiated",
	"TLS-021": "OCSP stapling not offered",
	"TLS-022": "HTTP/2 ALPN not negotiated",
	"TLS-030": "Handshake without SNI succeeded",
	"TLS-031": "Wrong-SNI handshake rejected",
	"TLS-032": "Wrong-SNI handshake still returned matching certificate",
	"TLS-033": "Wrong-SNI handshake returned different certificate",
	"TLS-050": "Weak TLS cipher accepted",
	"TLS-051": "Insecure TLS cipher accepted",
	"TLS-060": "TLS 1.2 session resumption not observed",
	"TLS-061": "TLS 1.3 session resumption not observed",
	"TLS-070": "Supported key exchange group observed",
	"TLS-080": "OCSP responder unreachable",
	"TLS-081": "OCSP responder returned unparseable response",
	"TLS-082": "OCSP responder reports certificate revoked",
	"TLS-083": "OCSP responder returned unknown status",
	"TLS-085": "Must-Staple required but stapling missing or invalid",
	"TLS-086": "Stapled OCSP: certificate revoked",
	"TLS-087": "Stapled OCSP status not good",
	"TLS-088": "CRL: certificate revoked",
	"TLS-089": "CRL fetch failed",
	"TLS-090": "Server cipher preference observed",
	"TLS-091": "TLS fallback SCSV not enforced",
}
